pipeline {
   agent none
   stages {
      stage('step 1') {
          agent any
          steps {
              echo 'Jenkins build is working for cmad-syslog-app'
          }
        }
      }
   post{
        always{
             echo 'the job is complete'
        }
  }
}