version: "3.7"
volumes:
  db-data1:

services:
  cmad-syslog-app:
    image: ruchika1706/syslog-app
    ports: 
      - 8081:8080
    depends_on:
      - mysql

  cmad-syslog-sender:
    image: ruchika1706/syslog-sender
    depends_on:
      - cmad-syslog-app


  mysql:
    image: mysql:5.7
    restart: always
    volumes: 
      - db-data1:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glarimy
    # ports:
    #   - '3306:3306'
    # expose: 
    #   - '3306'
    
