pipeline {
   agent none
   stages {
      stage('docker-package') {
          agent any
          steps {
              echo 'Packaging mysql with docker'
               script {
                   docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                       def usersImage = docker.build("ruchika1706/mysql:v${env.BUILD_ID}", "mysql")
                       usersImage.push()
                       usersImage.push("latest")
                   }
               }

        }
      }
   }
   post{
        always{
             echo 'the job is complete'
        }
  }
}